name: wosol
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.30.0+35
# version: 1.44.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  lottie: ^3.0.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  keep_screen_on: ^3.0.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  http: ^1.2.2
  device_info_plus: ^10.1.2
  # For Rating
  flutter_rating_bar: ^4.0.1
  # device_preview: ^1.1.0
  another_flushbar: ^1.12.30
  pretty_dio_logger: ^1.3.1
  package_info_plus: ^8.0.2

  launcher_name: ^1.0.2
  url_launcher: ^6.3.0
  intl: ^0.18.1
  # For location Service 
  permission_handler: ^11.3.1
  image_picker: ^1.1.0
  upgrader: ^10.3.0

launcher_name:
  default: "WOSOL"
  ar: "وسل"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/Urbanist/
    - assets/fonts/Noto/
    - assets/icons/
    - assets/images/
    - assets/images/home/
    - assets/lottie/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700

    - family: Noto
      fonts:
        - asset: assets/fonts/Noto/NotoSansArabic.ttf
          weight: 700
